
import dbObjects.DbResources;
import dbObjects.UserData;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JPanel;


public class LingoSphere3 extends javax.swing.JFrame {
    
    private DbResources db = new DbResources();
    static String logInMsg = "\nWelcome to Lingo Sphere, the language learning "+
        "tool developed by team JTA to facilitate foreign language learning and lesson "+
 "planning.\n\n"+
        "The program is intended for use by language students who need to review predetermined"+
        " vocabulary lists, instructors who need to set up language drills for class,  "
        + "and the casual user interested in looking for quick translation and proper"
        + " pronunciation of a particular word.  ";
    
    String userDataFilename = "userdata.txt" ;
    private ArrayList<User> userList = new ArrayList<>();
    
    public LingoSphere3() {
        initComponents();
        setLocationRelativeTo(null);
        
        welcomeMsg.setText(logInMsg);
        welcomeMsg.setLineWrap(true);
        welcomeMsg.setWrapStyleWord(true);
        welcomeMsg.setEditable(false); 
        systemMessages.setLineWrap(true);
        systemMessages.setWrapStyleWord(true);
        systemMessages.setEditable(false);
        setTitle(" Lingo Sphere German Translator");
        currentPsswdField.setColumns(14);
        currentUserField.setColumns(14);
        newUserField.setColumns(14);
        newPsswdField.setColumns(14);
        existingUserButton.setSelected(true);
        TeacherPage3 TeacherPages = new TeacherPage3() ;
        QuickTranslation translation = new QuickTranslation();
        
       // Initially, current user area enabled, new user disabled.
        
        Component[] comNU = newUserPanel.getComponents();
        Component[] comCU = currentUserPanel.getComponents();  
        for (int a = 0; a < comCU.length; a++) comCU[a].setEnabled(true);
        for (int a = 0; a < comNU.length; a++) comNU[a].setEnabled(false);
              
      /*  jTabbedPane1.addTab("Welcome"); 
        jTabbedPane2.addTab("Lesson Plan");
        jTabbedPane.addTab("Self Test");
        jTabbedPane.addTab("Graded Test");*/
        jTabbedPane2.addTab("Teacher's Page",TeacherPages);
        jTabbedPane2.addTab("Translation", translation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        currentUserPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        currentUserField = new javax.swing.JTextField();
        currentPsswdField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        newUserPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newUserField = new javax.swing.JTextField();
        newPsswdField = new javax.swing.JTextField();
        classNum = new javax.swing.JComboBox();
        accountType = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        existingUserButton = new javax.swing.JRadioButton();
        newUserButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        systemMessages = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        welcomeMsg = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Lingo Sphere"); // NOI18N

        jTabbedPane2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jTabbedPane2.setName("LingoSphere German Translator"); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        currentUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setText("Please log in:");

        currentUserField.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        currentUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentUserFieldActionPerformed(evt);
            }
        });

        currentPsswdField.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setText("Current User");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout currentUserPanelLayout = new javax.swing.GroupLayout(currentUserPanel);
        currentUserPanel.setLayout(currentUserPanelLayout);
        currentUserPanelLayout.setHorizontalGroup(
            currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentUserPanelLayout.createSequentialGroup()
                .addGroup(currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(currentUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(currentUserPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentPsswdField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(currentUserField)))
                    .addGroup(currentUserPanelLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        currentUserPanelLayout.setVerticalGroup(
            currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentUserPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(currentUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(currentPsswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleName(" Current User ");

        newUserPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setText("New User");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setText("Please create an account:");

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setText("New Username");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setText("New Password");

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Class Enrolled");

        jLabel12.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel12.setText("Account Type");

        newUserField.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserFieldActionPerformed(evt);
            }
        });

        newPsswdField.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newPsswdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPsswdFieldActionPerformed(evt);
            }
        });

        classNum.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        classNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GRM101", "SPN300", "JPN220", "FRN102" }));

        accountType.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        accountType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Instructor" }));
        accountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newUserPanelLayout = new javax.swing.GroupLayout(newUserPanel);
        newUserPanel.setLayout(newUserPanelLayout);
        newUserPanelLayout.setHorizontalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserPanelLayout.createSequentialGroup()
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newUserPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newUserPanelLayout.createSequentialGroup()
                                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(newUserPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(classNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPsswdField)))
                            .addComponent(jLabel8)))
                    .addGroup(newUserPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        newUserPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {newPsswdField, newUserField});

        newUserPanelLayout.setVerticalGroup(
            newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newPsswdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(classNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(newUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup5.add(existingUserButton);
        existingUserButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        existingUserButton.setSelected(true);
        existingUserButton.setText("Existing Account");
        existingUserButton.setActionCommand("existingUser");
        existingUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingUserButtonActionPerformed(evt);
            }
        });

        buttonGroup5.add(newUserButton);
        newUserButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        newUserButton.setText("New Account");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        systemMessages.setColumns(20);
        systemMessages.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        systemMessages.setForeground(new java.awt.Color(255, 0, 0));
        systemMessages.setRows(5);
        systemMessages.setText("System messages here");
        jScrollPane1.setViewportView(systemMessages);

        jLabel13.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel13.setText("Select New or Existing Account");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(existingUserButton)
                        .addGap(18, 18, 18)
                        .addComponent(newUserButton)
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(87, 87, 87))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingUserButton)
                    .addComponent(newUserButton))
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LSlogo2.jpg"))); // NOI18N

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setWheelScrollingEnabled(false);

        welcomeMsg.setColumns(20);
        welcomeMsg.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        welcomeMsg.setRows(8);
        jScrollPane2.setViewportView(welcomeMsg);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submitButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1299, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 605, Short.MAX_VALUE)
                    .addComponent(submitButton)
                    .addGap(0, 605, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(submitButton)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(currentUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(newUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentUserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Welcome", jPanel5);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        boolean validLogin = false;
        User userFound = new User();
        UserData dbUser = null;

        if (newUserButton.isSelected())
        {
            String newUsername = newUserField.getText() ;
            String newPsswd = newPsswdField.getText() ;
            Boolean isTeacher = false;
            
            if(String.valueOf(accountType.getSelectedItem()).equalsIgnoreCase("Instructor"))
                isTeacher = true;
            
            if ((newUsername.length() < 5) || (newPsswd.length() < 5))
            {
                systemMessages.setText("Password and username must be at least 5 characters");
            }
            else
            {
                userFound = addUser(userDataFilename) ;
                systemMessages.setText(userFound.welcomeUser());
                enablePanel(newUserPanel,false);
                
                try{
                    dbUser = db.createUser(newUsername , newPsswd, isTeacher);
                }
                catch(SQLException ex){
                    System.out.println("e: " + ex);
                }
            }
        }
        else  // Look for existing user
        {
            //userList = getUsers(userDataFilename);
            //for (User user: userList){
                try{
                    dbUser = db.getUser(currentUserField.getText() , currentPsswdField.getText());
                }
                catch(SQLException ex){
                    System.out.println("e: " + ex);
                }
                if (dbUser != null)
                {
                    validLogin = true;
                    //userFound = new User(user);
                }
                //}
            if (!validLogin)
            systemMessages.setText(" Invalid login. Please try again.");
            else
            {
                systemMessages.setText(userFound.welcomeUser());
                enablePanel(currentUserPanel,false);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        enablePanel(currentUserPanel,false);
        enablePanel(newUserPanel,true);
        //   newUserFlag = false;
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void existingUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingUserButtonActionPerformed
        enablePanel(currentUserPanel,true);
        enablePanel(newUserPanel,false);
        //   newUserFlag = false;
    }//GEN-LAST:event_existingUserButtonActionPerformed

    private void accountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeActionPerformed

    private void newPsswdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPsswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPsswdFieldActionPerformed

    private void newUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserFieldActionPerformed

    private void currentUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentUserFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LingoSphere3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LingoSphere3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LingoSphere3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LingoSphere3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LingoSphere3().setVisible(true);
            }
        });
    }
    // Read in all user accounts
     
    ArrayList<User> getUsers(String userFile)
    {
        ArrayList<User> userList = new ArrayList<>() ;
        FileInputStream fis = null ;
        BufferedReader reader = null ;
        File file =new File(userFile);
        
        if (!file.exists())return userList ;
        
        try{
            fis = new FileInputStream(userFile) ;
            reader = new BufferedReader(new InputStreamReader(fis));
            
    // For now, we're assuming the file is in the correct format so 
    // there are no error checks.
            
         String line = " " ;
         while (line != null)
          {
            line = reader.readLine() ;

            if (line != null){ 
                String username = line;
                String psswd = reader.readLine();
                String userType = reader.readLine() ;
                String className = reader.readLine() ; 
                
                line = reader.readLine() ;  //placeholders 
                line = reader.readLine() ;
                line = reader.readLine() ;
                line = reader.readLine() ;
                line = reader.readLine() ;
                line = reader.readLine() ;
                
                User UserToAdd = new User(username,psswd,userType, className);
                userList.add(UserToAdd); 
            }      
            }
        } 
        catch (FileNotFoundException ex) {} 
        catch (IOException ex){}
        finally 
        {
          try {
                reader.close();
                fis.close();
            } 
          catch(IOException ex){}
         };
        return userList;
    }
    
     User addUser(String userFile)
    {
        try{
    		File file =new File(userFile);
    		
    		//if file doesnt exists, then create it
    		if(!file.exists()){
    			file.createNewFile();
    		}
    		
    		//true = append file
    		FileWriter fw = new FileWriter(file.getName(),true);
    	        BufferedWriter writer = new BufferedWriter(fw);
                writer.write(newUserField.getText()+" \n") ;
    	        writer.write(newPsswdField.getText()+" \n");
                writer.write(accountType.getSelectedItem().toString()+" \n");
                writer.write(classNum.getSelectedItem().toString()+" \n");
                writer.write("*\n");
                writer.write("*\n");
                writer.write("*\n");
                writer.write("*\n");
                writer.write("*\n");
                writer.write("*\n");
    	        writer.close();
	        
    	}catch(IOException e){
    		e.printStackTrace();
    	}
        
        return new User(newUserField.getText(),newPsswdField.getText(),
                                accountType.getSelectedItem().toString(),
                                classNum.getSelectedItem().toString());
    }
    
    
 // Utility to disable/enable all components in a panel
    void enablePanel(JPanel panel, boolean enabled)
    {
          Component[] panelIO = panel.getComponents();
          for (int a = 0; a < panelIO.length; a++) {
                     panelIO[a].setEnabled(enabled);
          }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountType;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox classNum;
    private javax.swing.JTextField currentPsswdField;
    private javax.swing.JTextField currentUserField;
    private javax.swing.JPanel currentUserPanel;
    private javax.swing.JRadioButton existingUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField newPsswdField;
    private javax.swing.JRadioButton newUserButton;
    private javax.swing.JTextField newUserField;
    private javax.swing.JPanel newUserPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextArea systemMessages;
    private javax.swing.JTextArea welcomeMsg;
    // End of variables declaration//GEN-END:variables
}
